global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"] # Métricas do Collector
  # - job_name: "jaeger"
  #   static_configs:
  #     - targets: ["jaeger:14269"] # Métricas do Jaeger
